const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
const url=require('node:url').pathToFileURL(require('node:path').join(__dirname,'index.html')).href;
(async()=>{
 const b=await chromium.launch({headless:true}),ctx=await b.newContext({acceptDownloads:true,viewport:{width:1280,height:1000}}),p=await ctx.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(url);
 // Migrate an existing single-note record, without altering its legacy storage.
 await p.evaluate(()=>{const old=fresh();old.name='旧笔记';old.values[0].type='雅思AI';old.values[8].title='原来的标题';localStorage.setItem(KEY,JSON.stringify(old));});await p.reload();assert.equal(await p.locator('#post-name').inputValue(),'旧笔记');
 await p.locator('#field-0-type').fill('雅思AI干货');assert.match(await p.locator('#save-state').innerText(),/已保存 · \d/);
 await p.locator('[data-step="12"]').click();await p.locator('#reference-flow-1').click();await p.locator('#ref-0-A').setInputFiles(require('node:path').join(__dirname,'assets/workbench-icon.png'));await p.waitForFunction(()=>!!state.references[0].A);const originalImage=await p.evaluate(async()=>dataURL(await getAsset(state.references[0].A.id)));
 await p.locator('#reference-link').fill('https://example.com/original');await p.locator('#reference-borrow').fill('沿用自然光与留白');await p.evaluate(()=>{state.references[0].B={...state.references[0].A};save();});
 await p.reload();assert.equal(await p.locator('#stage-title').innerText(),'找参考与拍摄');await p.waitForFunction(()=>document.querySelector('.reference img').naturalWidth>0);
 await p.locator('#new-note').click();assert.equal(await p.locator('#note-picker option').count(),2);assert.equal(await p.locator('#field-0-type').inputValue(),'雅思AI干货');await p.locator('#post-name').fill('第二篇');await p.locator('[data-step="8"]').click();assert.equal(await p.locator('#field-8-title').inputValue(),'');await p.locator('#field-8-title').fill('第二篇标题');
 const ids=await p.locator('#note-picker option').evaluateAll(es=>es.map(e=>e.value));await p.locator('#note-picker').selectOption(ids[0]);assert.equal(await p.locator('#stage-title').innerText(),'找参考与拍摄');await p.locator('[data-step="8"]').click();assert.equal(await p.locator('#field-8-title').inputValue(),'原来的标题');
 await p.locator('#resume-note').fill('明天从第二个标题候选改');await p.locator('[data-step="4"]').click();assert.match(await p.locator('#resume-location').innerText(),/09 标题/);await p.locator('#resume-jump').click();assert.equal(await p.locator('#stage-title').innerText(),'标题');assert.match(await p.locator('#step-minimum').innerText(),/先留一个/);
 await p.locator('#note-picker').selectOption(ids[1]);assert.equal(await p.locator('#resume-note').inputValue(),'');await p.locator('#note-picker').selectOption(ids[0]);
 await p.close();const q=await ctx.newPage();await q.goto(url);assert.equal(await q.locator('#field-8-title').inputValue(),'原来的标题');
 assert.equal(await q.locator('#resume-note').inputValue(),'明天从第二个标题候选改');
 const d=q.waitForEvent('download');await q.locator('#backup-all').click();const dl=await d;const backup=JSON.parse(fs.readFileSync(await dl.path(),'utf8'));assert.equal(backup.library.notes.length,2);assert.equal(backup.assets.length,1);assert.equal(backup.assets[0].data,originalImage);
 // Restore into a separate clean browser profile; existing blank note is preserved.
 const ctx2=await b.newContext(),r=await ctx2.newPage();await r.goto(url);await r.locator('#backup-file').setInputFiles(await dl.path());await r.waitForFunction(()=>library.notes.length===3);assert.match(await r.locator('#post-name').inputValue(),/旧笔记（恢复）/);assert.equal(await r.locator('#resume-note').inputValue(),'明天从第二个标题候选改');await r.locator('[data-step="12"]').click();await r.waitForFunction(()=>document.querySelector('.reference img').naturalWidth>0);assert.equal(await r.evaluate(async()=>dataURL(await getAsset(state.references[0].A.id))),originalImage);
 assert.equal(await r.locator('#reference-link').inputValue(),'https://example.com/original');assert.equal(await r.locator('#reference-borrow').inputValue(),'沿用自然光与留白');await r.waitForFunction(()=>document.querySelectorAll('.reference img:not([hidden])').length===2);
 await r.locator('#backup-file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"format":"bad"}')});await r.waitForFunction(()=>document.querySelector('#library-status').textContent.includes('不是有效'));assert.equal(await r.locator('#note-picker option').count(),3);
 // Preserve the active note when it is not the first item; do not lose any imported fields.
 await q.locator('#note-picker').selectOption(ids[1]);await q.locator('[data-step="14"]').click();await q.locator('#revision-0').check();await q.locator('[data-step="9"]').click();await q.locator('#field-9-opening').fill('还没有写完的开头，备份也应该保留');
 const activeDownload=q.waitForEvent('download');await q.locator('#backup-all').click();const activeFile=await activeDownload;const activeBackup=JSON.parse(fs.readFileSync(await activeFile.path(),'utf8'));
 assert.equal(activeBackup.library.activeId,ids[1]);assert.equal(activeBackup.library.notes[1].step,9);
 const activeCtx=await b.newContext(),activePage=await activeCtx.newPage();await activePage.goto(url);
 await activePage.locator('#backup-file').setInputFiles({name:'active-second.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(activeBackup))});
 await activePage.waitForFunction(()=>library.notes.length===3);
 assert.equal(await activePage.locator('#post-name').inputValue(),'第二篇（恢复）');
 assert.deepEqual(await activePage.evaluate(()=>library.notes.slice(1).map(n=>n.values)),activeBackup.library.notes.map(n=>n.values));
 assert.equal(await activePage.locator('#stage-title').innerText(),'开头');assert.equal(await activePage.locator('#field-9-opening').inputValue(),'还没有写完的开头，备份也应该保留');
 const fields=['step','values','done','review','working','style','shots','revision','sources'];assert.deepEqual(await activePage.evaluate(keys=>Object.fromEntries(keys.map(k=>[k,state[k]])),fields),Object.fromEntries(fields.map(k=>[k,activeBackup.library.notes[1][k]])));
 await activePage.reload();assert.equal(await activePage.locator('#post-name').inputValue(),'第二篇（恢复）');assert.equal(await activePage.locator('#stage-title').innerText(),'开头');
 await activeCtx.close();
 // New demonstration and user-photo slots survive real backup/restore, without becoming original references.
 await q.locator('#note-picker').selectOption(ids[0]);await q.locator('[data-step="12"]').click();await q.locator('#reference-flow-2').click();
 const fixture=fs.readFileSync(require('node:path').join(__dirname,'assets/workbench-icon.png'));
 await q.locator('#ref-0-demo').setInputFiles({name:'new-demo.png',mimeType:'image/png',buffer:fixture});await q.waitForFunction(()=>!!state.references[0].demo);await q.locator('#reference-comparison').fill('保留真实学习痕迹');
 await q.locator('#reference-flow-3').click();await q.locator('#reference-plan').fill('窗边拍自己的书');await q.locator('summary').filter({hasText:'放入自己的试拍'}).click();await q.locator('#ref-0-shot').setInputFiles({name:'my-shot.png',mimeType:'image/png',buffer:fixture});await q.waitForFunction(()=>!!state.references[0].shot);await q.locator('#shot-0').check();
 const flowDownload=q.waitForEvent('download');await q.locator('#backup-all').click();const flowFile=await flowDownload,flowBackup=JSON.parse(fs.readFileSync(await flowFile.path(),'utf8'));assert.equal(flowBackup.assets.length,3);
 const flowCtx=await b.newContext(),flowPage=await flowCtx.newPage();await flowPage.goto(url);await flowPage.locator('#backup-file').setInputFiles(await flowFile.path());await flowPage.waitForFunction(()=>library.notes.length===3);
 assert.equal(await flowPage.locator('#reference-flow-3').getAttribute('aria-pressed'),'true');assert.equal(await flowPage.locator('#shot-0').isChecked(),true);assert.equal(await flowPage.locator('#reference-plan').inputValue(),'窗边拍自己的书');await flowPage.waitForFunction(()=>document.querySelector('.reference img').naturalWidth>0);
 for(const slot of ['A','B','demo','shot']){assert.equal(await flowPage.evaluate(async a=>dataURL(await getAsset(state.references[0][a].id)),slot),originalImage);assert.notEqual(await flowPage.evaluate(a=>state.references[0][a].id,slot),flowBackup.library.notes[0].references[0][slot].id);}
 await flowPage.locator('#reference-flow-2').click();assert.equal(await flowPage.locator('#reference-comparison').inputValue(),'保留真实学习痕迹');await flowPage.waitForFunction(()=>document.querySelectorAll('.reference img:not([hidden])').length===2);
 const missing=structuredClone(flowBackup);missing.assets=missing.assets.filter(a=>a.id!==missing.library.notes[0].references[0].demo.id);await flowPage.locator('#backup-file').setInputFiles({name:'missing-demo.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(missing))});await flowPage.waitForFunction(()=>document.querySelector('#library-status').textContent.includes('缺少参考图'));assert.equal(await flowPage.locator('#note-picker option').count(),3);
 const invalid=structuredClone(flowBackup);invalid.library.notes[0].references[0].demo={name:'bad'};await flowPage.locator('#backup-file').setInputFiles({name:'bad-demo.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(invalid))});await flowPage.waitForFunction(()=>document.querySelector('#library-status').textContent.includes('不是有效'));assert.equal(await flowPage.locator('#note-picker option').count(),3);await flowCtx.close();
 // Quota failure is visible and cannot cause new-note navigation to discard unsaved edits.
 await r.evaluate(()=>{Storage.prototype.setItem=function(){throw new Error('QuotaExceededError')};});await r.locator('#post-name').fill('仍在内存的草稿');await r.locator('#new-note').click();assert.equal(await r.locator('#post-name').inputValue(),'仍在内存的草稿');assert.match(await r.locator('#save-state').innerText(),/保存未成功/);
 // Quick capture reuses ordinary drafts and must never overwrite an existing topic.
 const quickCtx=await b.newContext({viewport:{width:1200,height:1000}}),k=await quickCtx.newPage();await k.goto(url);
 await k.locator('#post-name').fill('保留原笔记');await k.locator('#quick-capture summary').click();await k.locator('#save-quick').click();assert.equal(await k.locator('#note-picker option').count(),1);
 const scene='这个单词看得懂，但录音里总听不出来。';await k.locator('#quick-scene').fill(scene);await k.locator('#cancel-quick').click();assert.equal(await k.locator('#note-picker option').count(),1);await k.locator('#quick-capture summary').click();assert.equal(await k.locator('#quick-scene').inputValue(),scene);await k.locator('#save-quick').click();
 assert.equal(await k.locator('#note-picker option').count(),2);assert.equal(await k.locator('#field-4-scene').inputValue(),scene);assert.equal(await k.locator('#count').innerText(),'0/16步已完成');assert.equal(await k.evaluate(()=>state.values.filter((v,i)=>i!==4).every(v=>Object.keys(v).length===0)),true);
 await k.reload();assert.equal(await k.locator('#field-4-scene').inputValue(),scene);await k.locator('#scene-to-topic').click();assert.equal(await k.locator('#field-3-topic').inputValue(),scene);assert.equal(await k.locator('#field-3-need').inputValue(),'');await k.locator('#field-3-topic').fill('后来修改的选题');await k.locator('[data-step="4"]').click();await k.locator('#scene-to-topic').click();assert.equal(await k.locator('#field-3-topic').inputValue(),'后来修改的选题');
 await k.locator('[data-step="4"]').click();await k.locator('#quick-capture summary').click();await k.screenshot({path:'/tmp/workbench-quick.png',fullPage:true});await k.setViewportSize({width:390,height:900});assert.equal(await k.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await r.locator('#quick-capture summary').click();await r.locator('#quick-scene').fill('保存失败也不能丢掉这句话');await r.locator('#save-quick').click();assert.equal(await r.locator('#note-picker option').count(),3);assert.equal(await r.locator('#quick-scene').inputValue(),'保存失败也不能丢掉这句话');
 // Use a real sandbox directory handle to verify writes and persisted destination selection.
 const server=require('node:http').createServer((req,res)=>{const name=req.url==='/'?'index.html':req.url.slice(1);if(!['index.html','app.js','app.css'].includes(name)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',name.endsWith('.js')?'text/javascript':name.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(require('node:path').join(__dirname,name)));});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 const folderCtx=await b.newContext({acceptDownloads:true}),folderPage=await folderCtx.newPage();await folderPage.goto('http://127.0.0.1:'+server.address().port);
 await folderPage.evaluate(()=>{window.showDirectoryPicker=async()=>{const root=await navigator.storage.getDirectory();return root.getDirectoryHandle('备份测试目录',{create:true});};});
 await folderPage.locator('#backup-directory-settings summary').click();await folderPage.locator('#choose-backup-directory').click();await folderPage.waitForFunction(()=>document.querySelector('#library-status').textContent.includes('已记住'));
 await folderPage.locator('#post-name').fill('目录备份测试');await folderPage.locator('#backup-all').click();await folderPage.waitForFunction(()=>document.querySelector('#library-status').textContent.startsWith('已保存到'));
 const folderBackup=await folderPage.evaluate(async()=>{const root=await navigator.storage.getDirectory(),dir=await root.getDirectoryHandle('备份测试目录');const files=[];for await(const entry of dir.values())files.push(JSON.parse(await(await entry.getFile()).text()));return files;});assert.equal(folderBackup.length,1);assert.equal(folderBackup[0].library.notes[0].name,'目录备份测试');
 await folderPage.reload();await folderPage.waitForFunction(()=>document.querySelector('#backup-directory-state').textContent.includes('备份测试目录'));await folderPage.locator('#backup-all').click();await folderPage.waitForFunction(()=>document.querySelector('#library-status').textContent.startsWith('已保存到'));assert.equal(await folderPage.evaluate(async()=>{const dir=await(await navigator.storage.getDirectory()).getDirectoryHandle('备份测试目录');let n=0;for await(const e of dir.values())n++;return n;}),2);
 await folderPage.evaluate(()=>{backupDirectory={name:'拒绝授权的目录',queryPermission:async()=> 'denied',requestPermission:async()=> 'denied'};});let fallback=folderPage.waitForEvent('download');await folderPage.locator('#backup-all').click();await fallback;assert.match(await folderPage.locator('#library-status').innerText(),/未获授权/);
 await folderPage.evaluate(()=>{backupDirectory={name:'不可写的目录',queryPermission:async()=> 'granted',getFileHandle:async()=>{throw Error('write failed')}};});fallback=folderPage.waitForEvent('download');await folderPage.locator('#backup-all').click();await fallback;assert.match(await folderPage.locator('#library-status').innerText(),/写入指定目录失败/);
 await folderPage.locator('#backup-directory-settings summary').click();await folderPage.locator('#clear-backup-directory').click();await folderPage.waitForFunction(()=>backupDirectory===null);await folderPage.reload();await folderPage.waitForFunction(()=>document.querySelector('#backup-directory-state').textContent.includes('未指定目录'));await folderCtx.close();await new Promise(resolve=>server.close(resolve));
 await q.screenshot({path:'/tmp/workbench-library.png',fullPage:true});await q.setViewportSize({width:390,height:900});assert.equal(await q.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);await b.close();console.log('PASS: legacy migration, timestamps, close/reopen, independent notes, profile reuse, image-inclusive backup and clean-profile restore, invalid backup rejection, quota failure, mobile layout');
})().catch(e=>{console.error(e);process.exit(1)});
